name: CI

on: [push, pull_request, workflow_dispatch, repository_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - run: sudo apt-get update
    - uses: lix-pm/setup-lix@master
    - uses: HaxeFlixel/setup-flixel@master
    - uses: krdlab/setup-haxe@master
      with:
         haxe-version: 4.2.5
    - name: Build
      run:
      sudo apt-get install libvlc-dev
          sudo apt-get install libvlccore-dev
          haxelib setup ~/haxelib
          haxelib install hxcpp > /dev/null
          haxelib install lime
          haxelib install openfl
          haxelib --never install flixel
          haxelib run lime setup flixel
          haxelib run lime setup
          haxelib install flixel-tools
          haxelib install flixel-ui
          haxelib install flixel-addons
          haxelib install tjson
          haxelib install hxjsonast
          haxelib install hxCodec
          haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit
          haxelib install hscript
          haxelib git hscript-ex https://github.com/ianharrigan/hscript-ex
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib install hxcpp-debug-server
          haxelib list
          haxelib run lime build html5 -final
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        publish_dir: ./export/html5/bin
        force_orphan: true
      if: github.ref == 'refs/heads/master'
